// This file was generated by tfxjs
const tfxjs = require("tfxjs");
const tfx = new tfxjs("test_pattern/", "ibmcloud_api_key");

tfx.plan("tfx Generated Plan", () => {
  tfx.module(
    "Acceptance Tests",
    "module.acceptance_tests",
    tfx.resource(
      "Connection Management",
      'ibm_tg_connection.connection["management"]',
      {
        name: "icse-multi-vpc-management-hub-connection",
        network_type: "vpc",
        timeouts: {
          create: "30m",
          delete: "30m",
          update: null
        },
      }
    ),
    tfx.resource(
      "Connection Workload",
      'ibm_tg_connection.connection["workload"]',
      {
        name: "icse-multi-vpc-workload-hub-connection",
        network_type: "vpc",
        timeouts: {
          create: "30m",
          delete: "30m",
          update: null
        },
      }
    ),
    tfx.resource("Transit Gateway 0", "ibm_tg_gateway.transit_gateway[0]", {
      global: false,
      location: "us-south",
      name: "icse-multi-vpc-transit-gateway",
      resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
      timeouts: {
        create: "30m",
        delete: "30m",
        update: null
      },
    })
  );

  tfx.module(
    "Vpcs Management",
    'module.acceptance_tests.module.vpcs["management"]',
    tfx.resource("Vpc", "ibm_is_vpc.vpc", {
      address_prefix_management: "manual",
      classic_access: false,
      name: "icse-multi-vpc-management-vpc",
      resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
      tags: ["icse", "vpc"],
    })
  );

  tfx.module(
    "Public Gateways",
    'module.acceptance_tests.module.vpcs["management"].module.public_gateways',
    tfx.resource("Gateway Zone 1", 'ibm_is_public_gateway.gateway["zone-1"]', {
      name: "icse-multi-vpc-management-public-gateway-zone-1",
      resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
      zone: "us-south-1",
    }),
    tfx.resource("Gateway Zone 2", 'ibm_is_public_gateway.gateway["zone-2"]', {
      name: "icse-multi-vpc-management-public-gateway-zone-2",
      resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
      zone: "us-south-2",
    }),
    tfx.resource("Gateway Zone 3", 'ibm_is_public_gateway.gateway["zone-3"]', {
      name: "icse-multi-vpc-management-public-gateway-zone-3",
      resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
      zone: "us-south-3",
    })
  );

  tfx.module(
    "Address Prefixes",
    'module.acceptance_tests.module.vpcs["management"].module.address_prefixes',
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 1 1",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-1-1"]',
      {
        cidr: "10.5.0.0/16",
        is_default: false,
        name: "icse-multi-vpc-management-zone-1-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 1 2",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-1-2"]',
      {
        cidr: "10.10.10.0/24",
        is_default: false,
        name: "icse-multi-vpc-management-zone-1-2",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 1 3",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-1-3"]',
      {
        cidr: "10.10.30.0/24",
        is_default: false,
        name: "icse-multi-vpc-management-zone-1-3",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 2 1",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-2-1"]',
      {
        cidr: "10.6.0.0/16",
        is_default: false,
        name: "icse-multi-vpc-management-zone-2-1",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 2 2",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-2-2"]',
      {
        cidr: "10.20.10.0/24",
        is_default: false,
        name: "icse-multi-vpc-management-zone-2-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 3 1",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-3-1"]',
      {
        cidr: "10.7.0.0/16",
        is_default: false,
        name: "icse-multi-vpc-management-zone-3-1",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Address Prefixes Icse Multi Vpc Management Zone 3 2",
      'ibm_is_vpc_address_prefix.address_prefixes["icse-multi-vpc-management-zone-3-2"]',
      {
        cidr: "10.30.10.0/24",
        is_default: false,
        name: "icse-multi-vpc-management-zone-3-2",
        zone: "us-south-3",
      }
    )
  );

  tfx.module(
    "Security Groups",
    'module.acceptance_tests.module.vpcs["management"].module.security_groups',
    tfx.resource(
      "Security Group Test Group",
      'ibm_is_security_group.security_group["test-group"]',
      {
        name: "icse-multi-vpc-management-test-group",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules Test Group",
    'module.acceptance_tests.module.vpcs["management"].module.security_groups.module.security_group_rules["test-group"]',
    tfx.resource(
      "Default Vpc Rule Allow Ssh",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ssh"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "0.0.0.0/0",
        tcp: [
          {
            port_max: 22,
            port_min: 22,
          },
        ],
        udp: [],
      }
    )
  );

  tfx.module(
    "Network Acls",
    'module.acceptance_tests.module.vpcs["management"].module.network_acls',
    tfx.resource("Acl Bastion Acl", 'ibm_is_network_acl.acl["bastion-acl"]', {
      name: "icse-multi-vpc-management-bastion-acl",
      resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-ibm-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-all-network-inbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "allow-all-outbound",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-bastion-443-inbound",
          source: "0.0.0.0/0",
          tcp: [
            {
              port_max: 65535,
              port_min: 1,
              source_port_max: 443,
              source_port_min: 443,
            },
          ],
          udp: [],
        },
      ],
    }),
    tfx.resource(
      "Acl F5 External Acl",
      'ibm_is_network_acl.acl["f5-external-acl"]',
      {
        name: "icse-multi-vpc-management-f5-external-acl",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        rules: [
          {
            action: "allow",
            destination: "10.0.0.0/8",
            direction: "inbound",
            icmp: [],
            name: "allow-ibm-inbound",
            source: "161.26.0.0/16",
            tcp: [],
            udp: [],
          },
          {
            action: "allow",
            destination: "10.0.0.0/8",
            direction: "inbound",
            icmp: [],
            name: "allow-all-network-inbound",
            source: "10.0.0.0/8",
            tcp: [],
            udp: [],
          },
          {
            action: "allow",
            destination: "0.0.0.0/0",
            direction: "outbound",
            icmp: [],
            name: "allow-all-outbound",
            source: "0.0.0.0/0",
            tcp: [],
            udp: [],
          },
          {
            action: "allow",
            destination: "10.0.0.0/8",
            direction: "inbound",
            icmp: [],
            name: "allow-f5-external-443-inbound",
            source: "0.0.0.0/0",
            tcp: [
              {
                port_max: 443,
                port_min: 443,
                source_port_max: 65535,
                source_port_min: 1,
              },
            ],
            udp: [],
          },
        ],
      }
    ),
    tfx.resource(
      "Acl Management Acl",
      'ibm_is_network_acl.acl["management-acl"]',
      {
        name: "icse-multi-vpc-management-management-acl",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        rules: [
          {
            action: "allow",
            destination: "10.0.0.0/8",
            direction: "inbound",
            icmp: [],
            name: "allow-ibm-inbound",
            source: "161.26.0.0/16",
            tcp: [],
            udp: [],
          },
          {
            action: "allow",
            destination: "10.0.0.0/8",
            direction: "inbound",
            icmp: [],
            name: "allow-all-network-inbound",
            source: "10.0.0.0/8",
            tcp: [],
            udp: [],
          },
          {
            action: "allow",
            destination: "0.0.0.0/0",
            direction: "outbound",
            icmp: [],
            name: "allow-all-outbound",
            source: "0.0.0.0/0",
            tcp: [],
            udp: [],
          },
        ],
      }
    )
  );

  tfx.module(
    "Subnets",
    'module.acceptance_tests.module.vpcs["management"].module.subnets',
    tfx.resource(
      "Subnet Icse Multi Vpc Management Bastion Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-bastion-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.70.0/24",
        name: "icse-multi-vpc-management-bastion-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Bastion Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-bastion-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.70.0/24",
        name: "icse-multi-vpc-management-bastion-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Bastion Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-bastion-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.70.0/24",
        name: "icse-multi-vpc-management-bastion-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Bastion Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-bastion-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.60.0/24",
        name: "icse-multi-vpc-management-f5-bastion-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Bastion Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-bastion-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.60.0/24",
        name: "icse-multi-vpc-management-f5-bastion-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Bastion Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-bastion-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.60.0/24",
        name: "icse-multi-vpc-management-f5-bastion-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 External Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-external-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.40.0/24",
        name: "icse-multi-vpc-management-f5-external-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 External Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-external-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.40.0/24",
        name: "icse-multi-vpc-management-f5-external-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 External Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-external-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.40.0/24",
        name: "icse-multi-vpc-management-f5-external-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Management Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-management-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.30.0/24",
        name: "icse-multi-vpc-management-f5-management-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Management Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-management-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.30.0/24",
        name: "icse-multi-vpc-management-f5-management-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Management Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-management-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.30.0/24",
        name: "icse-multi-vpc-management-f5-management-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Workload Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-workload-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.50.0/24",
        name: "icse-multi-vpc-management-f5-workload-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Workload Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-workload-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.50.0/24",
        name: "icse-multi-vpc-management-f5-workload-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management F5 Workload Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-f5-workload-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.50.0/24",
        name: "icse-multi-vpc-management-f5-workload-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpe Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpe-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.80.0/24",
        name: "icse-multi-vpc-management-vpe-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpe Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpe-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.80.0/24",
        name: "icse-multi-vpc-management-vpe-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpe Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpe-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.80.0/24",
        name: "icse-multi-vpc-management-vpe-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn 1 Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-1-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.10.0/24",
        name: "icse-multi-vpc-management-vpn-1-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn 1 Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-1-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.10.0/24",
        name: "icse-multi-vpc-management-vpn-1-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn 1 Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-1-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.10.0/24",
        name: "icse-multi-vpc-management-vpn-1-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn 2 Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-2-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.5.20.0/24",
        name: "icse-multi-vpc-management-vpn-2-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn 2 Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-2-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.6.20.0/24",
        name: "icse-multi-vpc-management-vpn-2-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn 2 Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-2-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.7.20.0/24",
        name: "icse-multi-vpc-management-vpn-2-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vpn Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vpn-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.10.30.0/24",
        name: "icse-multi-vpc-management-vpn-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vsi Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vsi-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.10.10.0/24",
        name: "icse-multi-vpc-management-vsi-zone-1",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vsi Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vsi-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.20.10.0/24",
        name: "icse-multi-vpc-management-vsi-zone-2",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Management Vsi Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-management-vsi-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.30.10.0/24",
        name: "icse-multi-vpc-management-vsi-zone-3",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    )
  );

  tfx.module(
    "Vpcs Workload",
    'module.acceptance_tests.module.vpcs["workload"]',
    tfx.resource("Vpc", "ibm_is_vpc.vpc", {
      address_prefix_management: "auto",
      classic_access: false,
      name: "icse-multi-vpc-workload-vpc",
      resource_group: "29f5b3716d864498985b9725c649ad79",
      tags: ["icse", "vpc"],
    })
  );

  tfx.module(
    "Security Groups",
    'module.acceptance_tests.module.vpcs["workload"].module.security_groups',
    tfx.resource(
      "Security Group Test Group",
      'ibm_is_security_group.security_group["test-group"]',
      {
        name: "icse-multi-vpc-workload-test-group",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules Test Group",
    'module.acceptance_tests.module.vpcs["workload"].module.security_groups.module.security_group_rules["test-group"]',
    tfx.resource(
      "Default Vpc Rule Allow Ssh",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ssh"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "0.0.0.0/0",
        tcp: [
          {
            port_max: 22,
            port_min: 22,
          },
        ],
        udp: [],
      }
    )
  );

  tfx.module(
    "Network Acls",
    'module.acceptance_tests.module.vpcs["workload"].module.network_acls',
    tfx.resource("Acl Workload Acl", 'ibm_is_network_acl.acl["workload-acl"]', {
      name: "icse-multi-vpc-workload-workload-acl",
      resource_group: "29f5b3716d864498985b9725c649ad79",
      rules: [
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-ibm-inbound",
          source: "161.26.0.0/16",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "10.0.0.0/8",
          direction: "inbound",
          icmp: [],
          name: "allow-all-network-inbound",
          source: "10.0.0.0/8",
          tcp: [],
          udp: [],
        },
        {
          action: "allow",
          destination: "0.0.0.0/0",
          direction: "outbound",
          icmp: [],
          name: "allow-all-outbound",
          source: "0.0.0.0/0",
          tcp: [],
          udp: [],
        },
      ],
    })
  );

  tfx.module(
    "Subnets",
    'module.acceptance_tests.module.vpcs["workload"].module.subnets',
    tfx.resource(
      "Subnet Icse Multi Vpc Workload Vpe Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-workload-vpe-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.40.20.0/24",
        name: "icse-multi-vpc-workload-vpe-zone-1",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Workload Vpe Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-workload-vpe-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.50.20.0/24",
        name: "icse-multi-vpc-workload-vpe-zone-2",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Workload Vpe Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-workload-vpe-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.60.20.0/24",
        name: "icse-multi-vpc-workload-vpe-zone-3",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Workload Vsi Zone 1",
      'ibm_is_subnet.subnet["icse-multi-vpc-workload-vsi-zone-1"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.40.10.0/24",
        name: "icse-multi-vpc-workload-vsi-zone-1",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Workload Vsi Zone 2",
      'ibm_is_subnet.subnet["icse-multi-vpc-workload-vsi-zone-2"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.50.10.0/24",
        name: "icse-multi-vpc-workload-vsi-zone-2",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Icse Multi Vpc Workload Vsi Zone 3",
      'ibm_is_subnet.subnet["icse-multi-vpc-workload-vsi-zone-3"]',
      {
        ip_version: "ipv4",
        ipv4_cidr_block: "10.60.10.0/24",
        name: "icse-multi-vpc-workload-vsi-zone-3",
        resource_group: "29f5b3716d864498985b9725c649ad79",
        tags: ["icse", "vpc"],
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Prefix Icse Multi Vpc Workload Vpe Zone 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["icse-multi-vpc-workload-vpe-zone-1"]',
      {
        cidr: "10.40.20.0/24",
        is_default: false,
        name: "icse-multi-vpc-workload-vpe-zone-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix Icse Multi Vpc Workload Vpe Zone 2",
      'ibm_is_vpc_address_prefix.subnet_prefix["icse-multi-vpc-workload-vpe-zone-2"]',
      {
        cidr: "10.50.20.0/24",
        is_default: false,
        name: "icse-multi-vpc-workload-vpe-zone-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Prefix Icse Multi Vpc Workload Vpe Zone 3",
      'ibm_is_vpc_address_prefix.subnet_prefix["icse-multi-vpc-workload-vpe-zone-3"]',
      {
        cidr: "10.60.20.0/24",
        is_default: false,
        name: "icse-multi-vpc-workload-vpe-zone-3",
        zone: "us-south-3",
      }
    ),
    tfx.resource(
      "Subnet Prefix Icse Multi Vpc Workload Vsi Zone 1",
      'ibm_is_vpc_address_prefix.subnet_prefix["icse-multi-vpc-workload-vsi-zone-1"]',
      {
        cidr: "10.40.10.0/24",
        is_default: false,
        name: "icse-multi-vpc-workload-vsi-zone-1",
        zone: "us-south-1",
      }
    ),
    tfx.resource(
      "Subnet Prefix Icse Multi Vpc Workload Vsi Zone 2",
      'ibm_is_vpc_address_prefix.subnet_prefix["icse-multi-vpc-workload-vsi-zone-2"]',
      {
        cidr: "10.50.10.0/24",
        is_default: false,
        name: "icse-multi-vpc-workload-vsi-zone-2",
        zone: "us-south-2",
      }
    ),
    tfx.resource(
      "Subnet Prefix Icse Multi Vpc Workload Vsi Zone 3",
      'ibm_is_vpc_address_prefix.subnet_prefix["icse-multi-vpc-workload-vsi-zone-3"]',
      {
        cidr: "10.60.10.0/24",
        is_default: false,
        name: "icse-multi-vpc-workload-vsi-zone-3",
        zone: "us-south-3",
      }
    )
  );

  tfx.module(
    "Vpn Gateway",
    'module.acceptance_tests.module.vpcs["workload"].module.vpn_gateway',
    tfx.resource("Gateway 0", "ibm_is_vpn_gateway.gateway[0]", {
      mode: "route",
      name: "icse-multi-vpc-workload-gateway",
      resource_group: "29f5b3716d864498985b9725c649ad79",
      tags: ["icse", "vpc"],
      timeouts: {
        delete: "1h",
        create: null
      },
    })
  );

  tfx.module(
    "Security Groups F5 Bastion Sg",
    'module.acceptance_tests.module.security_groups["f5-bastion-sg"]',
    tfx.resource(
      "Security Group F5 Bastion Sg",
      'ibm_is_security_group.security_group["f5-bastion-sg"]',
      {
        name: "icse-multi-vpc-f5-bastion-sg",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules F5 Bastion Sg",
    'module.acceptance_tests.module.security_groups["f5-bastion-sg"].module.security_group_rules["f5-bastion-sg"]',
    tfx.resource(
      "Default Vpc Rule Allow 1 Inbound 3023",
      'ibm_is_security_group_rule.default_vpc_rule["allow-1-inbound-3023"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.5.70.0/24",
        tcp: [
          {
            port_max: 3025,
            port_min: 3023,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 1 Inbound 3080",
      'ibm_is_security_group_rule.default_vpc_rule["allow-1-inbound-3080"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.5.70.0/24",
        tcp: [
          {
            port_max: 3080,
            port_min: 3080,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 2 Inbound 3023",
      'ibm_is_security_group_rule.default_vpc_rule["allow-2-inbound-3023"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.6.70.0/24",
        tcp: [
          {
            port_max: 3025,
            port_min: 3023,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 2 Inbound 3080",
      'ibm_is_security_group_rule.default_vpc_rule["allow-2-inbound-3080"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.6.70.0/24",
        tcp: [
          {
            port_max: 3080,
            port_min: 3080,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 3 Inbound 3023",
      'ibm_is_security_group_rule.default_vpc_rule["allow-3-inbound-3023"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.7.70.0/24",
        tcp: [
          {
            port_max: 3025,
            port_min: 3023,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 3 Inbound 3080",
      'ibm_is_security_group_rule.default_vpc_rule["allow-3-inbound-3080"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.7.70.0/24",
        tcp: [
          {
            port_max: 3080,
            port_min: 3080,
          },
        ],
        udp: [],
      }
    )
  );

  tfx.module(
    "Security Groups F5 External Sg",
    'module.acceptance_tests.module.security_groups["f5-external-sg"]',
    tfx.resource(
      "Security Group F5 External Sg",
      'ibm_is_security_group.security_group["f5-external-sg"]',
      {
        name: "icse-multi-vpc-f5-external-sg",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules F5 External Sg",
    'module.acceptance_tests.module.security_groups["f5-external-sg"].module.security_group_rules["f5-external-sg"]',
    tfx.resource(
      "Default Vpc Rule Allow Inbound 443",
      'ibm_is_security_group_rule.default_vpc_rule["allow-inbound-443"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "0.0.0.0/0",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    )
  );

  tfx.module(
    "Security Groups Bastion Vsi Sg",
    'module.acceptance_tests.module.security_groups["bastion-vsi-sg"]',
    tfx.resource(
      "Security Group Bastion Vsi Sg",
      'ibm_is_security_group.security_group["bastion-vsi-sg"]',
      {
        name: "icse-multi-vpc-bastion-vsi-sg",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules Bastion Vsi Sg",
    'module.acceptance_tests.module.security_groups["bastion-vsi-sg"].module.security_group_rules["bastion-vsi-sg"]',
    tfx.resource(
      "Default Vpc Rule Allow All Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-all-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "0.0.0.0/0",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Inbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-inbound"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 443 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-443-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 53 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-53-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 53,
            port_min: 53,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 80 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-80-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 80,
            port_min: 80,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Inbound 443",
      'ibm_is_security_group_rule.default_vpc_rule["allow-inbound-443"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "0.0.0.0/0",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Vpc Inbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-vpc-inbound"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.0.0.0/8",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Vpc Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-vpc-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.0.0.0/8",
        tcp: [],
        udp: [],
      }
    )
  );

  tfx.module(
    "Security Groups F5 Management Sg",
    'module.acceptance_tests.module.security_groups["f5-management-sg"]',
    tfx.resource(
      "Security Group F5 Management Sg",
      'ibm_is_security_group.security_group["f5-management-sg"]',
      {
        name: "icse-multi-vpc-f5-management-sg",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules F5 Management Sg",
    'module.acceptance_tests.module.security_groups["f5-management-sg"].module.security_group_rules["f5-management-sg"]',
    tfx.resource(
      "Default Vpc Rule Allow 1 Inbound 22",
      'ibm_is_security_group_rule.default_vpc_rule["allow-1-inbound-22"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.5.70.0/24",
        tcp: [
          {
            port_max: 22,
            port_min: 22,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 1 Inbound 443",
      'ibm_is_security_group_rule.default_vpc_rule["allow-1-inbound-443"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.5.70.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 2 Inbound 22",
      'ibm_is_security_group_rule.default_vpc_rule["allow-2-inbound-22"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.6.70.0/24",
        tcp: [
          {
            port_max: 22,
            port_min: 22,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 2 Inbound 443",
      'ibm_is_security_group_rule.default_vpc_rule["allow-2-inbound-443"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.6.70.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 3 Inbound 22",
      'ibm_is_security_group_rule.default_vpc_rule["allow-3-inbound-22"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.7.70.0/24",
        tcp: [
          {
            port_max: 22,
            port_min: 22,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow 3 Inbound 443",
      'ibm_is_security_group_rule.default_vpc_rule["allow-3-inbound-443"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.7.70.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Inbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-inbound"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 443 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-443-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 53 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-53-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 53,
            port_min: 53,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 80 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-80-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 80,
            port_min: 80,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Vpc Inbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-vpc-inbound"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.0.0.0/8",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Vpc Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-vpc-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.0.0.0/8",
        tcp: [],
        udp: [],
      }
    )
  );

  tfx.module(
    "Security Groups F5 Workload Sg",
    'module.acceptance_tests.module.security_groups["f5-workload-sg"]',
    tfx.resource(
      "Security Group F5 Workload Sg",
      'ibm_is_security_group.security_group["f5-workload-sg"]',
      {
        name: "icse-multi-vpc-f5-workload-sg",
        resource_group: "afea64e05e4a42e3ac472fad14b8c3cd",
        tags: ["icse", "vpc"],
      }
    )
  );

  tfx.module(
    "Security Group Rules F5 Workload Sg",
    'module.acceptance_tests.module.security_groups["f5-workload-sg"].module.security_group_rules["f5-workload-sg"]',
    tfx.resource(
      "Default Vpc Rule Allow Ibm Inbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-inbound"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 443 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-443-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 53 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-53-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 53,
            port_min: 53,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Ibm Tcp 80 Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-ibm-tcp-80-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "161.26.0.0/16",
        tcp: [
          {
            port_max: 80,
            port_min: 80,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Vpc Inbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-vpc-inbound"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.0.0.0/8",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Vpc Outbound",
      'ibm_is_security_group_rule.default_vpc_rule["allow-vpc-outbound"]',
      {
        direction: "outbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.0.0.0/8",
        tcp: [],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Workload Subnet 1",
      'ibm_is_security_group_rule.default_vpc_rule["allow-workload-subnet-1"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.10.10.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Workload Subnet 2",
      'ibm_is_security_group_rule.default_vpc_rule["allow-workload-subnet-2"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.20.10.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Workload Subnet 3",
      'ibm_is_security_group_rule.default_vpc_rule["allow-workload-subnet-3"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.30.10.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Workload Subnet 4",
      'ibm_is_security_group_rule.default_vpc_rule["allow-workload-subnet-4"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.40.10.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Workload Subnet 5",
      'ibm_is_security_group_rule.default_vpc_rule["allow-workload-subnet-5"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.50.10.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    ),
    tfx.resource(
      "Default Vpc Rule Allow Workload Subnet 6",
      'ibm_is_security_group_rule.default_vpc_rule["allow-workload-subnet-6"]',
      {
        direction: "inbound",
        icmp: [],
        ip_version: "ipv4",
        remote: "10.60.10.0/24",
        tcp: [
          {
            port_max: 443,
            port_min: 443,
          },
        ],
        udp: [],
      }
    )
  );
});
